<?php
namespace CakeTaxonomy\Controller\Admin;

use Cake\Event\Event;
use CakeTaxonomy\Controller\AbstractTagsController;
use CakeTaxonomy\Controller\AppController;

/**
 * Tags Controller
 *
 * @property \CakeTaxonomy\Model\Table\TagsTable $Tags
 */
class TagsController extends AbstractTagsController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->deny();
    }
}
