<?php
namespace CakeTaxonomy\Controller\Admin;

use Cake\Event\Event;
use CakeTaxonomy\Controller\AbstractVocabulariesController;
use CakeTaxonomy\Controller\AppController;

/**
 * Vocabularies Controller
 *
 * @property \CakeTaxonomy\Model\Table\VocabulariesTable $Vocabularies
 */
class VocabulariesController extends AbstractVocabulariesController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->deny();
    }
}
